-- Ajout des colonnes manquantes à la table contrats
ALTER TABLE contrats
ADD COLUMN IF NOT EXISTS date_mise_a_jour TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
ADD COLUMN IF NOT EXISTS statut ENUM('actif', 'resilie') DEFAULT 'actif',
ADD COLUMN IF NOT EXISTS date_fin_reelle DATE,
ADD COLUMN IF NOT EXISTS motif_resiliation TEXT,
ADD COLUMN IF NOT EXISTS commentaires_resiliation TEXT,
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
